"use client";

import { createGlobalStyle } from "styled-components"

// @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600&display=swap');


//@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap');


const GlobalStyles = createGlobalStyle`
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap');   
  body {
    padding: 0;
    margin: 0;
    font-family: 'Roboto', sans-serif;
  }
`;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalStyles />
      <body>{children}</body>
    </html>
  )
}
